const Menu =[{
    id:1,
    image:"./images/maggie.jpg",
    name :"Maggie",
    category:"Dinner",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:2,
    image:"./images/burger.jpg",
    name :"burger",
    category:"Evening",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:3,
    image:"./images/naan.jpg",
    name :"naan",
    category:"lunch",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:5,
    image:"./images/sandwich.jpg",
    name :"sandwich",
    category:"lunch",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:6,
    image:"./images/biryani.jpg",
    name :"biryani",
    category:"Breakfast",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:7,
    image:"./images/dosa.jpg",
    name :"dosa",
    category:"Breakfast",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:8,
    image:"./images/gupchup.jpg",
    name :"Breakfast",
    category:"lunch",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:1,
    image:"./images/kheer.jpg",
    name :"kheer",
    category:"Dinner",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:1,
    image:"./images/rasmalai.jpg",
    name :"rasmalai",
    category:"Evening",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:1,
    image:"./images/rasmalai.jpg",
    name :"Sonnal",
    category:"Any",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
{
    id:1,
    image:"./images/rasmalai.jpg",
    name :"Sonal ",
    category:"Any",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},{
    id:1,
    image:"./images/rasmalai.jpg",
    name :"Sonal",
    category:"Any",
    price:25,
    description:" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic, provident atque. Libero, corporis. Eum?",
},
];
export default Menu;